name : Terraform with git actions

env:
  Messeage: Rahul creating IAM users with git actions


on: 
  push:
    branches: ["main", "master"]
  pull_request: 
    branches: ["main", "master"]

  workflow_dispatch:
    inputs:
      resource:
        type: choice
        description: Choose the resource
        options: 
          - name_of_dir1
          - name_of_dir2
      actions:
        description: 'Terraform Action to perform'
        type: choice
        options: 
        - Terraform_apply
        - Terraform_destroy

jobs:

  terraform_apply:
    name: 'terraform Apply'
    if: ${{ github.event.inputs.action == "Terraform_apply" }}
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_DEFAULT_REGION: us-east-1
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Terraform initialize
        id: init
        run: terraform init
        working-directory: "./iam_module/example"

      - name: Terraform Format
        id: fmt
        run: terraform fmt
        working-directory: "./iam_module/example"

      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: "./iam_module/example"

      - name: Terraform plan
        id: plan
        if: github.event_name == 'push'
        run: terraform plan
        working-directory: "./iam_module/example"

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: "./iam_module/example"
  
  terraform_destroy:
    name: Terraform Destroy
    if: ${{ github.event.inputs.action == "Terraform_destroy" }}
    runs-on: ubuntu-latest
    
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_DEFAULT_REGION: us-east-1
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

    steps:
      - name: checkout
        uses: actions/checout@v3

      - name: setup Terraform
        uses: hashicorp/setup-terraform@v2
        with: 
          terraform_version: 1.1.7

      - name: Terraform initialize
        id: init
        run: terraform init
        working-directory: "./iam_module/example"

      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve
        working-directory: "./iam_module/example"




      
      